export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const CREATE_CAMPAIGN_LOADING = "CREATE_CAMPAIGN_LOADING";
export const CREATE_CAMPAIGN_SUCCESS = "CREATE_CAMPAIGN_SUCCESS";
export const CREATE_CAMPAIGN_FAILURE = "CREATE_CAMPAIGN_FAILURE";

export const SUPPORTER_REGISTER_LOADING = "SUPPORTER_REGISTER_LOADING";
export const SUPPORTER_REGISTER_SUCCESS = "SUPPORTER_REGISTER_SUCCESS";
export const SUPPORTER_REGISTER_FAILURE = "SUPPORTER_REGISTER_FAILURE";

export const SUPPORTER_LOGIN_LOADING = "SUPPORTER_LOGIN_LOADING";
export const SUPPORTER_LOGIN_SUCCESS = "SUPPORTER_LOGIN_SUCCESS";
export const SUPPORTER_LOGIN_FAILURE = "SUPPORTER_LOGIN_FAILURE";

export const EDIT_CAMPAIGN_LOADING = "EDIT_CAMPAIGN_LOADING";
export const EDIT_CAMPAIGN_SUCCESS = "EDIT_CAMPAIGN_SUCCESS";
export const EDIT_CAMPAIGN_FAILURE = "EDIT_CAMPAIGN_FAILURE";

export const EDIT_MODAL_STATE = "EDIT_MODAL_STATE";

export const REGISTER_SUPPORTER_STORE_ID = "REGISTER_SUPPORTER_STORE_ID";
